// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./ISP1Verifier.sol";

/**
 * @title LLMAgentVault
 * @notice A DeFi vault managed by a verifiable Zero-Knowledge Machine Learning (zkML) model.
 * The model runs off-chain in the SP1 zkVM, generating trading decisions (BUY_ETH, BUY_USDC, HOLD)
 * along with a ZK proof. The vault verifies this proof before executing any trade.
 */
contract LLMAgentVault {
    // Events
    event Deposited(address indexed user, uint256 amount);
    event Withdrawn(address indexed user, uint256 amount);
    event Rebalanced(uint256[8] inputPrompt, uint256 actionToken, string actionName);
    
    // Custom Errors
    error InvalidProof();
    error Unauthorized();
    error TransferFailed();
    error InvalidActionToken(uint256 token);

    // The SP1 Verifier contract address
    address public immutable verifier;
    
    // The Program Verification Key (Image ID of our guest model)
    bytes32 public programVKey;
    
    // Owner of the vault
    address public owner;
    
    // Mock balances for tracking rebalancing logic
    uint256 public ethBalance;
    uint256 public usdcBalance;

    modifier onlyOwner() {
        if (msg.sender != owner) revert Unauthorized();
        _;
    }

    constructor(address _verifier, bytes32 _programVKey) {
        verifier = _verifier;
        programVKey = _programVKey;
        owner = msg.sender;
        
        // Start with some mock balances inside the vault
        usdcBalance = 10_000 * 10**6; // 10,000 USDC (6 decimals)
        ethBalance = 0;
    }

    /**
     * @notice Updates the verification key for the model (e.g., if we retrain the model).
     */
    function updateProgramVKey(bytes32 _newVKey) external onlyOwner {
        programVKey = _newVKey;
    }

    /**
     * @notice Performs a verified rebalancing action using a ZK proof of model inference.
     * @param publicValues The public inputs/outputs committed by the ZKVM:
     *                     - inputPrompt: uint256[8] (the encoded prompt tokens)
     *                     - actionToken: uint256 (the predicted action token)
     * @param proofBytes The Groth16 cryptographic proof seal generated by SP1.
     */
    function rebalance(
        bytes calldata publicValues,
        bytes calldata proofBytes
    ) external {
        // 1. Verify the SP1 ZK Proof
        // If the proof is invalid, this call will revert
        try ISP1Verifier(verifier).verifyProof(programVKey, publicValues, proofBytes) {
            // Proof is valid
        } catch {
            revert InvalidProof();
        }

        // 2. Decode the verified public values committed by the guest program
        // The ZKVM writes:
        //   sp1_zkvm::io::write(&input_idx); [8 values of uint256]
        //   sp1_zkvm::io::write(&pred_token); [1 value of uint256]
        (uint256[8] memory inputPrompt, uint256 actionToken) = abi.decode(
            publicValues,
            (uint256[8], uint256)
        );

        // 3. Execute the trading action
        string memory actionName;
        
        if (actionToken == 14) {
            // BUY_ETH (Token 14)
            // Mock Swap: Swap 50% of USDC balance to ETH (simulated at $3,000 per ETH)
            actionName = "BUY_ETH";
            uint256 usdcToSwap = usdcBalance / 2;
            if (usdcToSwap > 0) {
                usdcBalance -= usdcToSwap;
                // Add equivalent mock ETH (usdcToSwap / 3000 * 10^18 / 10^6)
                ethBalance += (usdcToSwap * 10**18) / (3000 * 10**6);
            }
        } else if (actionToken == 15) {
            // BUY_USDC (Token 15)
            // Mock Swap: Swap 50% of ETH balance to USDC (simulated at $3,000 per ETH)
            actionName = "BUY_USDC";
            uint256 ethToSwap = ethBalance / 2;
            if (ethToSwap > 0) {
                ethBalance -= ethToSwap;
                // Add equivalent mock USDC (ethToSwap * 3000 / 10^18 * 10^6)
                usdcBalance += (ethToSwap * 3000 * 10**6) / 10**18;
            }
        } else if (actionToken == 16) {
            // HOLD (Token 16)
            actionName = "HOLD";
            // Do nothing
        } else {
            revert InvalidActionToken(actionToken);
        }

        emit Rebalanced(inputPrompt, actionToken, actionName);
    }

    // Standard deposit/withdraw functions for vault management
    function deposit() external payable {
        ethBalance += msg.value;
        emit Deposited(msg.sender, msg.value);
    }

    function withdraw(uint256 amount) external onlyOwner {
        if (amount > address(this).balance) revert TransferFailed();
        payable(owner).transfer(amount);
        emit Withdrawn(owner, amount);
    }

    receive() external payable {
        ethBalance += msg.value;
    }
}
